import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import ClientProviders from "@/components/ui/ClientProviders";
import CartOverview from "@/components/cart/CartOverview";
import Footer from "@/components/ui/Footer";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fast React Pizza Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} antialiased`}
      >
        <ClientProviders>
          <div className="grid h-screen grid-rows-[auto_1fr_auto]">
            <Header />
            <div className="overflow-y-scroll">
              <main className="mx-auto max-w-3xl">{children}</main>
            </div>
            <Footer />
          </div>
          {/* Fixed position cart snackbar */}
          <CartOverview />
        </ClientProviders>
      </body>
    </html>
  );
}
